use crate::resources::map::{Terrain, TileMap};

/// Terrain rendering category — determines which sprite set to use.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TerrainGroup {
    Grass,
    Water,
    Dirt,
    Sand,
    Rock,
    Stone,
    Building,
    Special,
}

impl Terrain {
    pub fn group(&self) -> TerrainGroup {
        match self {
            Terrain::Grass | Terrain::LightForest | Terrain::DenseForest | Terrain::Garden => {
                TerrainGroup::Grass
            }
            Terrain::Water => TerrainGroup::Water,
            Terrain::Mud => TerrainGroup::Dirt,
            Terrain::Sand => TerrainGroup::Sand,
            Terrain::Rock => TerrainGroup::Rock,
            Terrain::Den
            | Terrain::Hearth
            | Terrain::Kitchen
            | Terrain::Stores
            | Terrain::Workshop => TerrainGroup::Building,
            Terrain::Wall | Terrain::Gate | Terrain::Watchtower | Terrain::WardPost => {
                TerrainGroup::Stone
            }
            Terrain::FairyRing
            | Terrain::StandingStone
            | Terrain::DeepPool
            | Terrain::AncientRuin => TerrainGroup::Special,
        }
    }
}

/// Whether a neighbor counts as "same" for overlay bitmask calculation.
/// Some terrain groups treat adjacent groups as friendly so their overlays
/// blend smoothly rather than producing isolated edge artifacts.
fn is_friendly(tile_group: TerrainGroup, neighbor_group: TerrainGroup) -> bool {
    if tile_group == neighbor_group {
        return true;
    }
    match tile_group {
        // Dirt/Sand blend into Grass (grass overlay at higher z covers the overlap)
        TerrainGroup::Dirt | TerrainGroup::Sand => neighbor_group == TerrainGroup::Grass,
        // Rock and Stone blend into each other
        TerrainGroup::Rock => neighbor_group == TerrainGroup::Stone,
        TerrainGroup::Stone => neighbor_group == TerrainGroup::Rock,
        // Grass defers to Dirt/Sand (symmetric full-fill, clean transition)
        // but renders scalloped edges toward Rock/Stone/Water/Building.
        // The grass overlay at z=3 sits above stone (z=2), so the grass
        // edges naturally layer over the stone edges.
        TerrainGroup::Grass => matches!(neighbor_group, TerrainGroup::Dirt | TerrainGroup::Sand),
        _ => false,
    }
}

/// 8-bit blob bitmask for all 8 neighbors. Diagonal bits are only set when
/// both adjacent cardinal neighbors are also present.
///
/// Bit layout (clockwise): N=1, NE=2, E=4, SE=8, S=16, SW=32, W=64, NW=128
///
/// This produces exactly 47 unique reduced values from the 256 possible raw
/// combinations. Each maps to a distinct autotile sprite.
pub fn blob_bitmask(map: &TileMap, x: i32, y: i32, group: TerrainGroup) -> u8 {
    let same = |dx: i32, dy: i32| -> bool {
        let nx = x + dx;
        let ny = y + dy;
        if !map.in_bounds(nx, ny) {
            return true;
        }
        is_friendly(group, map.get(nx, ny).terrain.group())
    };
    // TileMap is Y-down: visual north = y-1, visual south = y+1.
    let n = same(0, -1);
    let e = same(1, 0);
    let s = same(0, 1);
    let w = same(-1, 0);

    let mut mask = 0u8;
    if n {
        mask |= 1;
    }
    if n && e && same(1, -1) {
        mask |= 2;
    } // NE
    if e {
        mask |= 4;
    }
    if e && s && same(1, 1) {
        mask |= 8;
    } // SE
    if s {
        mask |= 16;
    }
    if s && w && same(-1, 1) {
        mask |= 32;
    } // SW
    if w {
        mask |= 64;
    }
    if w && n && same(-1, -1) {
        mask |= 128;
    } // NW
    mask
}

/// 4-bit bitmask for cardinal neighbors only (kept for non-blob terrain types).
/// Bit layout: N=0x1, E=0x2, S=0x4, W=0x8
pub fn cardinal_bitmask(map: &TileMap, x: i32, y: i32, group: TerrainGroup) -> u8 {
    let mut mask = 0u8;
    let same = |dx: i32, dy: i32| -> bool {
        let nx = x + dx;
        let ny = y + dy;
        if !map.in_bounds(nx, ny) {
            return true;
        }
        map.get(nx, ny).terrain.group() == group
    };
    if same(0, -1) {
        mask |= 0x1;
    }
    if same(1, 0) {
        mask |= 0x2;
    }
    if same(0, 1) {
        mask |= 0x4;
    }
    if same(-1, 0) {
        mask |= 0x8;
    }
    mask
}

/// Atlas index for the 8-bit blob grass overlay.
/// The 8x8 atlas has 47 blob tiles (slots 0-46) and 12 decorative center
/// variants (slots 47-58). Generated by tools/build_grass_atlas.py.
#[rustfmt::skip]
const BLOB_TO_ATLAS: [u32; 256] = [
     0,  1,  0,  0,  2,  3,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0, // 0-15
     5,  6,  0,  0,  7,  8,  0,  9,  0,  0,  0,  0, 10, 11,  0, 12, // 16-31
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 32-47
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 48-63
    13, 14,  0,  0, 15, 16,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0, // 64-79
    18, 19,  0,  0, 20, 21,  0, 22,  0,  0,  0,  0, 23, 24,  0, 25, // 80-95
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 96-111
    26, 27,  0,  0, 28, 29,  0, 30,  0,  0,  0,  0, 31, 32,  0, 33, // 112-127
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 128-143
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 144-159
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 160-175
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 176-191
     0, 34,  0,  0,  0, 35,  0, 36,  0,  0,  0,  0,  0,  0,  0,  0, // 192-207
     0, 37,  0,  0,  0, 38,  0, 39,  0,  0,  0,  0,  0, 40,  0, 41, // 208-223
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, // 224-239
     0, 42,  0,  0,  0, 43,  0, 44,  0,  0,  0,  0,  0, 45,  0, 46, // 240-255
];

const CENTER_FILL_INDEX: u32 = 46;
const DECORATIVE_BASE: u32 = 47;
const DECORATIVE_COUNT: u32 = 12;

/// Maps 8-bit blob bitmask to grass overlay atlas index.
pub fn grass_overlay_atlas_index(bitmask: u8) -> u32 {
    BLOB_TO_ATLAS[bitmask as usize]
}

/// Maps blob bitmask to atlas index, with decorative center fill variants.
/// For center fill tiles (bitmask 255), uses a position-based hash to select
/// one of 12 decorative variants with a ~30% chance.
pub fn grass_overlay_atlas_index_with_variant(bitmask: u8, x: i32, y: i32) -> u32 {
    let base = BLOB_TO_ATLAS[bitmask as usize];
    if base == CENTER_FILL_INDEX {
        let hash = (x as u32)
            .wrapping_mul(7)
            .wrapping_add((y as u32).wrapping_mul(13));
        if hash % 10 < 3 {
            DECORATIVE_BASE + (hash / 10) % DECORATIVE_COUNT
        } else {
            base
        }
    } else {
        base
    }
}

/// Base layer tile index for terrain.
pub fn base_tile_index(terrain: &Terrain) -> u32 {
    match terrain.group() {
        TerrainGroup::Grass | TerrainGroup::Special => 0,
        TerrainGroup::Water => 1,
        TerrainGroup::Dirt => 2,
        TerrainGroup::Sand => 3,
        TerrainGroup::Rock => 4,
        TerrainGroup::Stone => 5,
        TerrainGroup::Building => 6,
    }
}

/// Whether this terrain should have a grass overlay rendered on top.
pub fn has_grass_overlay(terrain: &Terrain) -> bool {
    matches!(terrain.group(), TerrainGroup::Grass | TerrainGroup::Special)
}

/// Terrain groups that have blob autotile overlays, with their atlas paths and z-order.
pub struct OverlayConfig {
    pub group: TerrainGroup,
    pub atlas_path: &'static str,
    pub z: f32,
}

/// All overlay layers, ordered by z (bottom to top).
/// Grass is highest so its scalloped edges render on top of other terrain.
pub const OVERLAY_LAYERS: &[OverlayConfig] = &[
    OverlayConfig {
        group: TerrainGroup::Dirt,
        atlas_path: "sprites/soil_autotile_atlas.png",
        z: 1.0,
    },
    OverlayConfig {
        group: TerrainGroup::Sand,
        atlas_path: "sprites/soil_autotile_atlas.png",
        z: 1.0,
    },
    OverlayConfig {
        group: TerrainGroup::Rock,
        atlas_path: "sprites/stone_autotile_atlas.png",
        z: 2.0,
    },
    OverlayConfig {
        group: TerrainGroup::Stone,
        atlas_path: "sprites/stone_autotile_atlas.png",
        z: 2.0,
    },
    OverlayConfig {
        group: TerrainGroup::Grass,
        atlas_path: "sprites/grass_autotile_atlas.png",
        z: 3.0,
    },
    OverlayConfig {
        group: TerrainGroup::Special,
        atlas_path: "sprites/grass_autotile_atlas.png",
        z: 3.0,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    fn make_map(terrain: &[&[Terrain]]) -> TileMap {
        let height = terrain.len() as i32;
        let width = terrain[0].len() as i32;
        let mut map = TileMap::new(width, height, Terrain::Water);
        for (y, row) in terrain.iter().enumerate() {
            for (x, &t) in row.iter().enumerate() {
                map.set(x as i32, y as i32, t);
            }
        }
        map
    }

    #[test]
    fn surrounded_grass_has_full_bitmask() {
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        assert_eq!(blob_bitmask(&map, 1, 1, TerrainGroup::Grass), 255);
    }

    #[test]
    fn isolated_grass_has_zero_bitmask() {
        let map = make_map(&[
            &[Terrain::Water, Terrain::Water, Terrain::Water],
            &[Terrain::Water, Terrain::Grass, Terrain::Water],
            &[Terrain::Water, Terrain::Water, Terrain::Water],
        ]);
        assert_eq!(blob_bitmask(&map, 1, 1, TerrainGroup::Grass), 0);
    }

    #[test]
    fn diagonal_only_set_when_both_cardinals_present() {
        // NE grass present, but only N cardinal — NE bit should NOT be set
        let map = make_map(&[
            &[Terrain::Water, Terrain::Grass, Terrain::Grass],
            &[Terrain::Water, Terrain::Grass, Terrain::Water],
            &[Terrain::Water, Terrain::Water, Terrain::Water],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Grass);
        assert_eq!(mask & 1, 1, "N should be set");
        assert_eq!(mask & 2, 0, "NE should NOT be set (E cardinal absent)");
    }

    #[test]
    fn diagonal_set_when_both_cardinals_present() {
        // N, E, and NE all grass — NE bit should be set
        let map = make_map(&[
            &[Terrain::Water, Terrain::Grass, Terrain::Grass],
            &[Terrain::Water, Terrain::Grass, Terrain::Grass],
            &[Terrain::Water, Terrain::Water, Terrain::Water],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Grass);
        assert_eq!(mask & 1, 1, "N set");
        assert_eq!(mask & 2, 2, "NE set");
        assert_eq!(mask & 4, 4, "E set");
    }

    #[test]
    fn out_of_bounds_counts_as_same_group() {
        let map = make_map(&[&[Terrain::Grass]]);
        assert_eq!(blob_bitmask(&map, 0, 0, TerrainGroup::Grass), 255);
    }

    #[test]
    fn north_edge_bitmask() {
        // North is water, rest is grass — should produce N edge (124)
        let map = make_map(&[
            &[Terrain::Water, Terrain::Water, Terrain::Water],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        // E(4) + SE(8) + S(16) + SW(32) + W(64) = 124
        assert_eq!(blob_bitmask(&map, 1, 1, TerrainGroup::Grass), 124);
    }

    #[test]
    fn inner_corner_bitmask() {
        // All neighbors grass except diagonal NE — should produce NE inner corner
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Water],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        // All cardinal + SE(8) + SW(32) + W... wait let me compute
        // N(1) + NE(0, NE is water) + E(4) + SE(8) + S(16) + SW(32) + W(64) + NW(128)
        // = 1+4+8+16+32+64+128 = 253
        assert_eq!(blob_bitmask(&map, 1, 1, TerrainGroup::Grass), 253);
    }

    #[test]
    fn atlas_lookup_covers_all_47_values() {
        let valid_bitmasks: Vec<u8> = vec![
            0, 1, 4, 5, 7, 16, 17, 20, 21, 23, 28, 29, 31, 64, 65, 68, 69, 71, 80, 81, 84, 85, 87,
            92, 93, 95, 112, 113, 116, 117, 119, 124, 125, 127, 193, 197, 199, 209, 213, 215, 221,
            223, 241, 245, 247, 253, 255,
        ];
        assert_eq!(valid_bitmasks.len(), 47);
        let mut atlas_indices: Vec<u32> = valid_bitmasks
            .iter()
            .map(|&m| grass_overlay_atlas_index(m))
            .collect();
        atlas_indices.sort();
        atlas_indices.dedup();
        assert_eq!(
            atlas_indices.len(),
            47,
            "all 47 should map to distinct indices"
        );
        assert_eq!(*atlas_indices.last().unwrap(), 46);
    }

    #[test]
    fn decorative_variant_stable_for_same_position() {
        let a = grass_overlay_atlas_index_with_variant(255, 5, 3);
        let b = grass_overlay_atlas_index_with_variant(255, 5, 3);
        assert_eq!(a, b);
    }

    #[test]
    fn decorative_variant_only_for_center_fill() {
        // Non-center bitmask should never return a decorative index
        let idx = grass_overlay_atlas_index_with_variant(124, 5, 3);
        assert!(idx < 47);
    }

    #[test]
    fn dirt_treats_grass_as_friendly() {
        // Mud tile surrounded by grass should get full bitmask (not isolated)
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Mud, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        assert_eq!(blob_bitmask(&map, 1, 1, TerrainGroup::Dirt), 255);
    }

    #[test]
    fn dirt_at_water_boundary_has_edge() {
        // Mud between water (north) and grass (south) — should show north edge
        let map = make_map(&[
            &[Terrain::Water, Terrain::Water, Terrain::Water],
            &[Terrain::Grass, Terrain::Mud, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Dirt);
        assert_eq!(mask & 1, 0, "N should NOT be set (water is not friendly)");
        assert_eq!(mask & 4, 4, "E should be set (grass is friendly)");
        assert_eq!(mask & 16, 16, "S should be set (grass is friendly)");
    }

    #[test]
    fn grass_treats_dirt_as_friendly() {
        // Grass defers to Dirt's own overlay — no grass edge toward mud
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Mud, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Grass);
        assert_eq!(
            mask & 64,
            64,
            "W should be set (grass defers to dirt's overlay)"
        );
    }

    #[test]
    fn grass_not_friendly_to_water() {
        // Water has no overlay, so grass renders its own edge
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Water, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Grass);
        assert_eq!(mask & 64, 0, "W should NOT be set (water has no overlay)");
    }

    #[test]
    fn grass_renders_edge_toward_stone() {
        // Stone has its own overlay at z=2, but grass (z=3) should render
        // its scalloped edge on top — not defer with a flat full-fill.
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Wall, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Grass);
        assert_eq!(
            mask & 64,
            0,
            "W should NOT be set (grass renders edge toward stone)"
        );
    }

    #[test]
    fn grass_renders_edge_toward_rock() {
        let map = make_map(&[
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
            &[Terrain::Rock, Terrain::Grass, Terrain::Grass],
            &[Terrain::Grass, Terrain::Grass, Terrain::Grass],
        ]);
        let mask = blob_bitmask(&map, 1, 1, TerrainGroup::Grass);
        assert_eq!(
            mask & 64,
            0,
            "W should NOT be set (grass renders edge toward rock)"
        );
    }

    #[test]
    fn forest_counts_as_grass_group() {
        assert_eq!(Terrain::LightForest.group(), TerrainGroup::Grass);
        assert_eq!(Terrain::DenseForest.group(), TerrainGroup::Grass);
        assert_eq!(Terrain::Garden.group(), TerrainGroup::Grass);
    }

    #[test]
    fn terrain_group_classification() {
        assert_eq!(Terrain::Water.group(), TerrainGroup::Water);
        assert_eq!(Terrain::Rock.group(), TerrainGroup::Rock);
        assert_eq!(Terrain::Den.group(), TerrainGroup::Building);
        assert_eq!(Terrain::Wall.group(), TerrainGroup::Stone);
        assert_eq!(Terrain::Sand.group(), TerrainGroup::Sand);
    }
}
